In [1]:
import numpy as np
import pandas as pd

In [2]:
# first dataframe
df1 = pd.DataFrame({
    'id': ['a', 'b', 'c', 'd'],
    'prop_1' : [4,8,9,2],
    'prop_2' : [1,6,5,2]
})


# second dataframe
df2 = pd.DataFrame({
    'id': ['g', 'd', 'h', 'a'],
    'prop_1' : [8,5,0,3],
    'prop_2' : [5,1,7,4]
})

In [3]:
df1

  id  prop_1  prop_2
0  a       4       1
1  b       8       6
2  c       9       5
3  d       2       2

In [4]:
df2

  id  prop_1  prop_2
0  g       8       5
1  d       5       1
2  h       0       7
3  a       3       4

In [6]:
# merge with common values in `id` column
df3 = pd.merge(df1, df2, on='id', how='inner')
df3

  id  prop_1_x  prop_2_x  prop_1_y  prop_2_y
0  a         4         1         3         4
1  d         2         2         5         1

In [10]:
# merge with values in `id` column of df1 only
df3 = pd.merge(df1, df2, on='id', how='left')
df3

  id  prop_1_x  prop_2_x  prop_1_y  prop_2_y
0  a         4         1       3.0       4.0
1  b         8         6       NaN       NaN
2  c         9         5       NaN       NaN
3  d         2         2       5.0       1.0

In [12]:
# merge with values in `id` column of df2 only
df3 = pd.merge(df1, df2, on='id', how='right')
df3

  id  prop_1_x  prop_2_x  prop_1_y  prop_2_y
0  g       NaN       NaN         8         5
1  d       2.0       2.0         5         1
2  h       NaN       NaN         0         7
3  a       4.0       1.0         3         4

In [15]:
# add suffixes
# merge with common values in `id` column
df3 = pd.merge(df1, df2, on='id', how='inner', suffixes=['_df1', '_df2'])
df3

  id  prop_1_df1  prop_2_df1  prop_1_df2  prop_2_df2
0  a           4           1           3           4
1  d           2           2           5           1